config/routes.rb
Rails.application.routes.draw do
  get "search", to: "search#search"

  resources :planets, only: %i[index show]
  resources :species, only: %i[index show]
  resources :films, only: %i[index show]

  root to: "index#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/climate.rb
class Climate < ApplicationRecord
  has_many :planetary_climates
  has_many :planets, through: :planetary_climates
end

app/models/film.rb
class Film < ApplicationRecord
  has_many :planet_appearances
  has_many :planets, through: :planet_appearances

  has_many :species_appearances
  has_many :species, through: :species_appearances

  validates :title, :episode, :opening_crawl, presence: true
  validates :episode, numericality: true
  validates :title, :episode, uniqueness: true

  def self.search(search_term)
    where("LOWER(title) LIKE ?", "%#{search_term.downcase}%")
  end
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :planetary_terrains
  has_many :terrains, through: :planetary_terrains

  has_many :planetary_climates
  has_many :climates, through: :planetary_climates

  has_many :planet_appearances
  has_many :films, through: :planet_appearances

  has_many :species

  validates :name, presence: true
  validates :name, uniqueness: true

  def climates_list
    climates.map(&:name).join(", ").humanize
  end

  def terrains_list
    terrains.map(&:name).join(", ").humanize
  end

  def self.search(search_term)
    where("LOWER(name) LIKE ?", "%#{search_term.downcase}%")
  end
end

app/models/planet_appearance.rb
class PlanetAppearance < ApplicationRecord
  belongs_to :planet
  belongs_to :film

  validates :planet, :film, presence: true
end

app/models/planetary_climate.rb
class PlanetaryClimate < ApplicationRecord
  belongs_to :climate
  belongs_to :planet

  validates :planet, :climate, presence: true
end

app/models/planetary_terrain.rb
class PlanetaryTerrain < ApplicationRecord
  belongs_to :planet
  belongs_to :terrain

  validates :planet, :terrain, presence: true
end

app/models/species.rb
class Species < ApplicationRecord
  belongs_to :planet, optional: true

  has_many :species_appearances
  has_many :films, through: :species_appearances

  validates :name, :classification, :designation, :average_lifespan, presence: true
  validates :name, uniqueness: true

  def self.search(search_term)
    where("LOWER(name) LIKE ?", "%#{search_term.downcase}%")
  end
end

app/models/species_appearance.rb
class SpeciesAppearance < ApplicationRecord
  belongs_to :species
  belongs_to :film
end

app/models/terrain.rb
class Terrain < ApplicationRecord
  has_many :planetary_terrains
  has_many :planets, through: :planetary_terrains

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  def index
    @films = Film.order("episode ASC")
  end

  def show
    @film = Film.find(params[:id])
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
    @films = Film.limit(3).order("RANDOM()")
    @planets = Planet.limit(3).order("RANDOM()")
    @species = Species.limit(3).order("RANDOM()")
  end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.includes(:climates, :terrains).order("name ASC")
  end

  def show
    @planet = Planet.find(params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    search_type = params[:search_type].to_i
    search_term = params[:search_term]
    @results = case search_type
               when 1
                 Film.search(search_term)
               when 2
                 Planet.search(search_term)
               when 3
                 Species.search(search_term)
               else
                 Film.search(search_term) + Planet.search(search_term) + Species.search(search_term)
               end
  end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  def index
    @species = Species.includes(:planet).order("name ASC")
  end

  def show
    @s_species = Species.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/films/_film.html.erb
<div class="col mb-5 d-flex align-items-stretch">
  <div class="card" style="width: 18rem;">
    <h5 class="card-header">Episode <%= film.episode %>: <%= film.title %></h5>
    <div class="card-body d-flex flex-column">
      <h5 class="card-title">Released: <%= film.release_date %></h5>
      <p class="card-text"><%= film.opening_crawl.truncate(100) %></p>
      <%= link_to 'Details', film, class: "btn mt-auto btn-primary" %>
    </div>
  </div>
</div>

app/views/films/index.html.erb
<div class="container">
  <h1>Star Wars Films</h1>
  <div class="row">
    <%= render partial: 'film', collection: @films %>
  </div>
</div>

app/views/films/show.html.erb
<div class="container">
  <div class="card">
    <h5 class="card-header">Episode <%= @film.episode %>: <%= @film.title %></h5>
    <div class="card-body">
      <h5 class="card-title">Released: <%= @film.release_date %></h5>
      <p class="card-text"><%= @film.opening_crawl %></p>
    </div>
    <h5 class="card-header">Species Featured</h5>
    <ul class="list-group list-group-flush">
        <% @film.species.each do |sp| %>
          <li class="list-group-item"><%= link_to sp.name, sp %></li>
        <% end %>
    </ul>
    <h5 class="card-header">Planets Featured</h5>
    <ul class="list-group list-group-flush">
        <% @film.planets.each do |planet| %>
          <li class="list-group-item"><%= link_to planet.name, planet %></li>
        <% end %>
    </ul>
    <div class="card-body">
    <%= link_to 'All Films', films_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/planets/_planet.html.erb
<div class="col mb-5 d-flex align-items-stretch">
  <div class="card" style="width: 18rem;">
    <h5 class="card-header"><%= planet.name %></h5>
    <div class="card-body d-flex flex-column">
      <% unless planet.climates.count == 0 &&  planet.terrains.count == 0 %>
        <h5 class="card-title">Geography</h5>
        <% unless planet.climates.count %>
          <p class="card-text"><%= 'Climate'.pluralize(planet.climates.count) %>: <%= planet.climates_list %></p>
        <% end %>
        <% unless planet.terrains.count == 0 %>
          <p class="card-text"><%= 'Terrain'.pluralize(planet.terrains.count) %>: <%= planet.terrains_list %></p>
        <% end %>
      <% end %>
      <%= link_to 'Details', planet, class: "btn mt-auto btn-primary" %>
    </div>
  </div>
</div>

app/views/planets/index.html.erb
<div class="container">
  <h1>Star Wars Planets</h1>
  <div class="row">
    <%= render partial: 'planet', collection: @planets %>
  </div>
</div>

app/views/planets/show.html.erb
<div class="container">
  <div class="card">
    <h5 class="card-header"><%= @planet.name %></h5>
    <div class="card-body">
      <% unless @planet.climates.count == 0 &&  @planet.terrains.count == 0 %>
        <h5 class="card-title">Geography</h5>
        <% unless @planet.climates.count == 0 %>
          <p class="card-text"><%= 'Climate'.pluralize(@planet.climates.count) %>: <%= @planet.climates_list %></p>
        <% end %>
        <% unless @planet.terrains.count == 0 %>
          <p class="card-text"><%= 'Terrain'.pluralize(@planet.terrains.count) %>: <%= @planet.terrains_list %></p>
        <% end %>
      <% end %>
    </div>
    <% if @planet.films.count > 0 %>
      <h5 class="card-header">Featured in films</h5>
      <ul class="list-group list-group-flush">
        <% @planet.films.each do |film| %>
          <li class="list-group-item"><%= link_to film.title, film %></li>
        <% end %>
      </ul>
    <% end %>
    <% if @planet.species.count > 0 %>
      <h5 class="card-header">Species</h5>
      <ul class="list-group list-group-flush">
        <% @planet.species.each do |sp| %>
          <li class="list-group-item"><%= link_to sp.name, sp %></li>
        <% end %>
      </ul>
    <% end %>
    <div class="card-body">
    <%= link_to 'All Planets', planets_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>

app/views/search/index.html.erb
<div class="container">

</div>

app/views/search/search.html.erb
<div class="container">
  <div class="row">
    <%= render @results %>
  </div>
</div>

app/views/species/_species.html.erb
<div class="col mb-5 d-flex align-items-stretch">
  <div class="card" style="width: 18rem;">
    <h5 class="card-header"><%= species.name %></h5>
    <div class="card-body d-flex flex-column">
      <% unless species.planet.nil? %>
        <h5 class="card-title">Homeworld: <%= species.planet.name %></h5>
      <% end %>
      <% unless species.designation.nil? %>
        <p class="card-text">Designation: <%= species.designation %></p>
      <% end %>
      <% unless species.classification.nil? %>
        <p class="card-text">Classification: <%= species.classification %></p>
      <% end %>

      <%= link_to 'Details', species, class: "btn mt-auto btn-primary" %>
    </div>
  </div>
</div>

app/views/species/index.html.erb
<div class="container">
  <h1>Star Wars Species</h1>
  <div class="row">
    <%= render partial: 'species', collection: @species %>
  </div>
</div>

app/views/species/show.html.erb
<div class="container">
  <div class="card">
    <h5 class="card-header"><%= @s_species.name %></h5>
    <div class="card-body">
      <% unless @s_species.planet.nil? %>
        <h5 class="card-title">Homeworld</h5>
        <p class="card-text"><%= link_to @s_species.planet.name, @s_species.planet %></p>
      <% end %>
      <h5 class="card-title">Characteristics</h5>
      <p class="card-text">Designation: <%= @s_species.designation.humanize %></p>
      <p class="card-text">Classification: <%= @s_species.classification.humanize %></p>
      <p class="card-text">Average Lifespan: <%= @s_species.average_lifespan %></p>
    </div>
    <h5 class="card-header">Featured in films</h5>
    <ul class="list-group list-group-flush">
      <% @s_species.films.each do |film| %>
        <li class="list-group-item"><%= link_to film.title, film %></li>
      <% end %>
    </ul>
    <div class="card-body">
    <%= link_to 'All Species', species_index_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>